# action.yml
name: 'Hello Baeldung'
description: 'Greet Baeldung and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'Baeldung'
outputs:
  time: # id of output
    description: 'The time we greeted Baeldung'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
