on: [push]

jobs:
  hello_baeldung_job:
    runs-on: ubuntu-latest
    name: A job to say hello to Baeldung
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello Baeldung action step
        uses: ./ # Uses an Docker container action in the root directory
        id: hello
        with:
          who-to-greet: 'Baeldung'
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
